---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
- name: Install base packages
  ansible.builtin.apt:
    name:
      - vim
      - htop
      - curl
      - git
    state: present
- name: Create deploy user
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
- name: Add SSH key for deploy user
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', ssh_pubkey_path) }}"
- name: Allow passwordless sudo for deploy user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ deploy_user }}
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"
