---
- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
- name: Allow required TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allow_tcp }}"
- name: Enable UFW with deny incoming
  community.general.ufw:
    state: enabled
    policy: deny
  register: ufw_enabled
  changed_when: "'Skipping' not in (ufw_enabled.stdout | default(''))"
