---
- name: Prepare web server
  hosts: web
  become: true
  gather_facts: true
  roles:
    - role: common
      tags:
        - common
    - role: firewall
      tags:
        - firewall
    - role: nginx
      tags:
        - nginx
