---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Ensure nginx running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: Render site config from template
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/site.conf
    mode: "0644"
  notify: Restart nginx
- name: Enable site symlink
  ansible.builtin.file:
    src: /etc/nginx/sites-available/site.conf
    dest: /etc/nginx/sites-enabled/site.conf
    state: link
    force: true
  notify: Restart nginx
- name: Remove default site if present
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
- name: Deploy index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"
  notify: Restart nginx
