name: Deploy (Terraform → Ansible)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_cloud_id:       ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id:      ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_ssh_user:       ${{ secrets.SSH_USER }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- Terraform ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write SA key (for provider)
        working-directory: terraform
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false

      - name: Grab public IP
        id: tf-output
        working-directory: terraform
        run: |
          ip=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$ip" >> $GITHUB_ENV
          echo "Public IP: $ip"

      # ---------- Ansible ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: pip install --disable-pip-version-check ansible==9.6.0

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$PUBLIC_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          cat > inventory.ini <<EOF
          [web]
          ${PUBLIC_IP} ansible_user=${{ secrets.SSH_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa
          EOF
          ansible -i inventory.ini web -m ping
          ansible-playbook -i inventory.ini playbooks/site.yml
